book-store-ecommerce/Controllers/BooksController.cs
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class BooksController : Controller
    {
        private readonly IBooksService _service;

        public BooksController(IBooksService service)  //inject db context in constructor
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allBooks = await _service.GetAllAsync(n => n.Provider); //order by name
            return View(allBooks);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString) 
        {
            var allBooks = await _service.GetAllAsync(n => n.Provider); //order by name
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allBooks.Where(n => n.Name.ToLower().Contains(searchString.ToLower())).ToList();

                return View("Index",filteredResult);
            }
            return View("Index", allBooks);
        }

        //GET: Books/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var bookDetail = await _service.GetBookByIdAsync(id);
            return View(bookDetail);
        }

        //GET: Book/Create
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
            ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
            ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
           {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
                ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
                ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");
                return View(book);
           }
            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //GET: Book/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound"); // if book doesn t exist show Notfound page

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Name = bookDetails.Name,
                Description = bookDetails.Description,
                Price = bookDetails.Price,
                ISBN = bookDetails.ISBN,
                ImageUrl = bookDetails.ImageUrl,
                BookCategory = bookDetails.BookCategory,
                PublishingHouseId = bookDetails.PublishingHouseId,
                ProviderId = bookDetails.ProviderId,
                WriterIds = bookDetails.Writers_Books.Select(n => n.WriterId).ToList(),
            };

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
            ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
            ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM book)
        {
            if (id != book.Id) return View("NotFound"); // if book doesn t exist show Notfound page


            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
                ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
                ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");
                return View(book);
            }
            await _service.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

    }
}

book-store-ecommerce/Controllers/OrdersController.cs
using book_store_ecommerce.Data.Cart;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace book_store_ecommerce.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {

        private readonly IBooksService _booksService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IBooksService booksService, ShoppingCart shoppingCart, IOrdersService ordersService) 
        {
            _booksService= booksService;
            _shoppingCart= shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); //get user id and user role values
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _booksService.GetBookByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _booksService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

book-store-ecommerce/Controllers/ProvidersController.cs
using book_store_ecommerce.Data;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProvidersController : Controller
    {

        private readonly IProvidersService _service;

        public ProvidersController(IProvidersService service)  //inject db context in constructor
        {

            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProviders = await _service.GetAllAsync();
            return View(allProviders);
        }


        //Get: Providers/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Provider provider)
        {
            if (!ModelState.IsValid)
            {
                return View(provider);
            }
            await _service.AddAsync(provider);
            return RedirectToAction(nameof(Index));
        }

        //Get: Providers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if(providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        //Get: Provider/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Provider provider)
        {
            if (!ModelState.IsValid)
            {
                return View(provider);
            }
            await _service.UpdateAsync(id,provider);
            return RedirectToAction(nameof(Index));
        }

        //Get: Provider/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

book-store-ecommerce/Controllers/WritersController.cs
using book_store_ecommerce.Data;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    //check if you're logged 
    public class WritersController : Controller
    {
        private readonly IWritersService _service; 

        public WritersController(IWritersService service)  //inject db context in constructor
        {
            _service = service;
        }
        [AllowAnonymous]  // allow unauthenticated users
        public async Task<IActionResult> Index() //Show all writers
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //Get: Writers/Create
        public IActionResult Create() //create writer
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfileImageUrl,FullName,Bio")] Writer writer)
        {
            if (!ModelState.IsValid)                 //checks if models state required is valid - delete <Nullable>enable<Nullable> in order to work, only valid for .NET 6
            {
                return View(writer);
            }

            await _service.AddAsync(writer);
            return RedirectToAction(nameof(Index));
        }



        //Get: Writers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
                
            return View(writerDetails);
        }


        //Get: Writers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
            return View(writerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfileImageUrl,FullName,Bio")] Writer writer)                     //edit writer
        {
            if (!ModelState.IsValid)
            {
                return View(writer);
            }
            await _service.UpdateAsync(id, writer);
            return RedirectToAction(nameof(Index));
        }


        //Get:Writers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if(writerDetails == null)
            {
                return View("NotFound");
            }
            return View(writerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

book-store-ecommerce/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3"> 
            <h1 class="text-info"> PAGE NOT FOUND</h1>
    <hr />
            <a class="justify-center btn btn-outline-success" asp-controller="Writers" asp-action="Index">Home Page</a>
    </div>
</div>

book-store-ecommerce/Views/Shared/_CreateItem.cshtml
@model string;
@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle">Add New</i></a>
</div>
}

book-store-ecommerce/Views/Shared/_Identity.cshtml
@* injecting to make value dynamic*@
@inject UserManager<ApplicationUser> userManager; 


@if (!User.Identity.IsAuthenticated) //check user Is not Authenticated show these buttons
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right">Login</i>
    </a>

    <span syle="padding: 5px;"></span>


    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus">Register</i>
    </a>
}
else
{
    @*User profile section*@
    <div class="dropdown">
        <button class="btn alert-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @userManager.GetUserName(User);
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropwdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list">Orders</i>
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropwdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people">Users</i>
                    </a>
                </li>
            }
   
        </ul>
    </div>

    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"> Log out</i>
        </button>
    </form>
}

book-store-ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - book_store_ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/book_store_ecommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class ="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="Books" asp-action="Index"><i class="badge-alert-info bi bi-book"></i>Books</a>
                        </li>


                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown show">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i>Management
                                </a>


                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Providers" asp-action="Index"><i class="bi bi-truck"> Providers</i></a>
                                    <a class="dropdown-item" asp-controller="PublishingHouses" asp-action="Index"><i class="bi bi-house-door"> Publishing Houses</i></a>
                                    <a class="dropdown-item" asp-controller="Writers" asp-action="Index"><i class="bi bi-pen-fill"> Writers</i></a>
                                </div>


                            </li>
                        }

                    </ul>



                    <form class="form-inline my-2 my-lg-0 d-flex" asp-controller="Books" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a book.." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                 <!--  <div class="d-md-inline">
                    <div class="bi-cart-check-fill" style="list-style: none">
                    </div>
                   </div>
                   -->

                       <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")                    
                       </ul>

                      <partial name="_Identity.cshtml"></partial>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="text-center text-lg-start bg-blue text-muted">

        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">

            <div class="me-5 d-none d-lg-block">
            </div>

            <div>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>

        </section>

        <section class="">
            <div class="container text-center text-md-start mt-5">

                <div class="row mt-3">

                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>BookStore
                        </h6>
                        <p>
                            "Enlighten yourself"
                        </p>
                    </div>
 

                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

                        <h6 class="text-uppercase fw-bold mb-4">
                            Get to know us
                        </h6>
                        <p>
                            <a href="#!" class="text-reset">Blog</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Careers</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">About Us</a>
                        </p>
                        <p>
                            <a href="#!" class="text-reset">Help</a>
                        </p>
                    </div>

                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@bookstore.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                        <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                    </div>

                </div>

            </div>
        </section>

        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2023 Copyright:
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>