book-store-ecommerce/Controllers/BooksController.cs
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class BooksController : Controller
    {
        private readonly IBooksService _service;

        public BooksController(IBooksService service)  //inject db context in constructor
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allBooks = await _service.GetAllAsync(n => n.Provider); //order by name
            return View(allBooks);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString) 
        {
            var allBooks = await _service.GetAllAsync(n => n.Provider); //order by name
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allBooks.Where(n => n.Name.ToLower().Contains(searchString.ToLower())).ToList();

                return View("Index",filteredResult);
            }
            return View("Index", allBooks);
        }

        //GET: Books/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var bookDetail = await _service.GetBookByIdAsync(id);
            return View(bookDetail);
        }

        //GET: Book/Create
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
            ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
            ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
           {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
                ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
                ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");
                return View(book);
           }
            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //GET: Book/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound"); // if book doesn t exist show Notfound page

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Name = bookDetails.Name,
                Description = bookDetails.Description,
                Price = bookDetails.Price,
                ISBN = bookDetails.ISBN,
                ImageUrl = bookDetails.ImageUrl,
                BookCategory = bookDetails.BookCategory,
                PublishingHouseId = bookDetails.PublishingHouseId,
                ProviderId = bookDetails.ProviderId,
                WriterIds = bookDetails.Writers_Books.Select(n => n.WriterId).ToList(),
            };

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
            ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
            ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM book)
        {
            if (id != book.Id) return View("NotFound"); // if book doesn t exist show Notfound page


            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Providers = new SelectList(bookDropdownsData.Providers, "Id", "Name");
                ViewBag.PublishingHouses = new SelectList(bookDropdownsData.PublishingHouses, "Id", "FullName");
                ViewBag.Writers = new SelectList(bookDropdownsData.Writers, "Id", "FullName");
                return View(book);
            }
            await _service.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

    }
}

book-store-ecommerce/Controllers/OrdersController.cs
using book_store_ecommerce.Data.Cart;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace book_store_ecommerce.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {

        private readonly IBooksService _booksService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IBooksService booksService, ShoppingCart shoppingCart, IOrdersService ordersService) 
        {
            _booksService= booksService;
            _shoppingCart= shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier); //get user id and user role values
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _booksService.GetBookByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _booksService.GetBookByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

book-store-ecommerce/Controllers/ProvidersController.cs
using book_store_ecommerce.Data;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProvidersController : Controller
    {

        private readonly IProvidersService _service;

        public ProvidersController(IProvidersService service)  //inject db context in constructor
        {

            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProviders = await _service.GetAllAsync();
            return View(allProviders);
        }


        //Get: Providers/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Provider provider)
        {
            if (!ModelState.IsValid)
            {
                return View(provider);
            }
            await _service.AddAsync(provider);
            return RedirectToAction(nameof(Index));
        }

        //Get: Providers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if(providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        //Get: Provider/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Provider provider)
        {
            if (!ModelState.IsValid)
            {
                return View(provider);
            }
            await _service.UpdateAsync(id,provider);
            return RedirectToAction(nameof(Index));
        }

        //Get: Provider/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            return View(providersDetails);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmation(int id)
        {
            var providersDetails = await _service.GetByIdAsync(id);
            if (providersDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

book-store-ecommerce/Controllers/PublishingHousesController.cs
using book_store_ecommerce.Data;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class PublishingHousesController : Controller
    {
        private readonly IPublishingHousesService _service;

        public PublishingHousesController(IPublishingHousesService  service) //inject in constructor
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var publishingHouses = await _service.GetAllAsync();
            return View(publishingHouses);
        }

        //GET: PublishingHouses/Create/
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureUrl,FullName,About")] PublishingHouse publishingHouse)
        {
            if (!ModelState.IsValid)
            {
                return View(publishingHouse);
            }
            await _service.AddAsync(publishingHouse);
            return RedirectToAction(nameof(Index));
        }

        //GET: PublishingHouses/details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id) //check if data exists in db, if exits return to view
        {
            var publishingHousesDetails = await _service.GetByIdAsync(id);
            if (publishingHousesDetails == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(publishingHousesDetails);
            }

        }
        //GET: PublishingHouses/edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var publishingHousesDetails = await _service.GetByIdAsync(id);
            if(publishingHousesDetails == null)
            {
                return View("NotFound");
                    }
            return View(publishingHousesDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind( "Id,ProfilePictureUrl,FullName,About")] PublishingHouse publishingHouse)
        {
            if (!ModelState.IsValid)
            {
                return View(publishingHouse);
            }
            if(id == publishingHouse.Id)
            {
            await _service.UpdateAsync(id, publishingHouse);
            return RedirectToAction(nameof(Index));
            }
            return View(publishingHouse);
        }

        //GET: PublishingHouses/delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var publishingHousesDetails = await _service.GetByIdAsync(id);
            if (publishingHousesDetails == null)
            {
                return View("NotFound");
            }
            return View(publishingHousesDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publishingHousesDetails = await _service.GetByIdAsync(id);
            if (publishingHousesDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

book-store-ecommerce/Controllers/WritersController.cs
using book_store_ecommerce.Data;
using book_store_ecommerce.Data.Services;
using book_store_ecommerce.Data.Static;
using book_store_ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace book_store_ecommerce.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    //check if you're logged 
    public class WritersController : Controller
    {
        private readonly IWritersService _service; 

        public WritersController(IWritersService service)  //inject db context in constructor
        {
            _service = service;
        }
        [AllowAnonymous]  // allow unauthenticated users
        public async Task<IActionResult> Index() //Show all writers
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //Get: Writers/Create
        public IActionResult Create() //create writer
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfileImageUrl,FullName,Bio")] Writer writer)
        {
            if (!ModelState.IsValid)                 //checks if models state required is valid - delete <Nullable>enable<Nullable> in order to work, only valid for .NET 6
            {
                return View(writer);
            }

            await _service.AddAsync(writer);
            return RedirectToAction(nameof(Index));
        }



        //Get: Writers/Details/1
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
                
            return View(writerDetails);
        }


        //Get: Writers/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
            return View(writerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfileImageUrl,FullName,Bio")] Writer writer)                     //edit writer
        {
            if (!ModelState.IsValid)
            {
                return View(writer);
            }
            await _service.UpdateAsync(id, writer);
            return RedirectToAction(nameof(Index));
        }


        //Get:Writers/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if(writerDetails == null)
            {
                return View("NotFound");
            }
            return View(writerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var writerDetails = await _service.GetByIdAsync(id);

            if (writerDetails == null)
            {
                return View("NotFound");
            }
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

book-store-ecommerce/Views/Books/Create.cshtml
@model NewBookVM
@using book_store_ecommerce.Data

@{
    ViewData["Title"] = "Create a new book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new book</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ISBN" class="control-label"></label>
                                <input asp-for="ISBN" class="form-control" />
                                <span asp-validation-for="ISBN" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="ProviderId" class="control-label"></label>
                                <select asp-for="ProviderId" class="form-control" asp-items="ViewBag.Providers"></select>
                                <span asp-validation-for="ProviderId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-label"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublishingHouseId" class="control-label"></label>
                                <select asp-for="PublishingHouseId" class="form-control" asp-items="ViewBag.PublishingHouses"></select>
                                <span asp-validation-for="PublishingHouseId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="WriterIds" class="control-label"></label>
                                <select asp-for="WriterIds" class="form-control" asp-items="ViewBag.Writers" multiple></select>
                                <span asp-validation-for="WriterIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>


@section Scripts{ 
    <script>
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

book-store-ecommerce/Views/Books/Details.cshtml
@model Book
@{
   ViewData["Title"] = "Book details";
}

<div class = "row">
           <div class="col-md-8 offset-2"> 
               <div class="card mb-3" style="max-width: 700px">
                   <div class="row g-0">
                       <div class="col-md-12">
                           <div class="card-header text-white bg-info">
                               <p class="card-text">
                                   <h5 class="card-title">
                                       @Model.Name
                                   </h5>
                               </p>
                           </div>
                       </div>
                       <div class="col-md-4">
                           <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                       </div>
                       <div class="col-md-8">
                           <div class="card-body">
                               <p class="cart-text">@Model.Name</p>
                               <p class="cart-text">
                                   <b>Provider: </b>
                                   <a asp-controller="Providers" asp-action="Details" asp-route-id="@Model.ProviderId">
                                       @Model.Provider.Name
                                   </a>
                               </p>

                                                              <p class="cart-text">
                                   <b>Publishing House: </b>
                                   <a asp-controller="PublishingHouses" asp-action="Details" asp-route-id="@Model.PublishingHouseId">
                                       @Model.PublishingHouse.FullName
                                   </a>
                               </p>
                               <p class="cart-text"><b>ISBN: </b>@Model.ISBN</p>
                               <p class="cart-text"><b>Category: </b>@Model.BookCategory</p>
                                                <!--              <p class="cart-text">
                                   <b>Status:</b>
                                  if(item.Pieces == 0){
                                       <span class="badge bg-succes text-white"> STOCK EMPTY</span>
                                   }else if(item.Pieces <=5){
                                       <span class="badge bg-succes text-white">LIMIT STOCK</span>
                                   }else{
                                       <span class="badge bg-succes text-white">IN STOCK</span>
                                   }
                               </p>
                               NOTE: MIGRATE DB AND UPDATE AFTER COLUMN PIECES in BOOK MODEL INSERTED
                               -->
                               <p class="card-text">
                                   <b>Writers: </b>
                                   <hr />
                                   <div class="row">
                                @foreach (var writer in Model.Writers_Books)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@writer.Writer.ProfileImageUrl" style="max-width: 150px"/>
                                        <br/>
                                        <a asp-controller="Writers" asp-action="Details" asp-route-id="@writer.WriterId">@writer.Writer.FullName</a>
                                    </div>
                                }
                            </div>
                               </p>
                           </div>
                       </div>

                       <div class="col-md-12">
                           <div class="card-footer">
                        <p class="card-text d-flex justify-content-between">
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i>Add to Cart($@Model.Price.ToString("c")</a>
                                   <a class="btn btn-primary float-right" asp-action="Index">
                                       Back to List
                                       </a>
                                  
                               </p>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
    
</div>

book-store-ecommerce/Views/Books/Index.cshtml
@model IEnumerable<Book>
@{
   ViewData["Title"] = "List of Books";
}

<div class = "row">
    @foreach(var item in Model)
    {
           <div class="col-md-4 col-xs-6 border-alert-primary mb-3"> 
               <div class="card mb-3" style="max-width: 700px">
                   <div class="row g-0">
                       <div class="col-md-12">
                           <div class="card-header text-white bg-info">
                               <p class="card-text">
                                   <h5 class="card-title">
                                       @item.Name
                                    @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                   </h5>
                               </p>
                           </div>
                       </div>
                       <div class="col-md-6">
                        <img src="@item.ImageUrl" style="width: 100%; height: 25vw; object-fit: fill;" alt="@item.Name">
                       </div>
                       <div class="col-md-6">
                           <div class="card-body">
                               <p class="cart-text">@item.Name</p>
                               <p class="cart-text"><b>Provider: </b>@item.Provider.Name</p>
                               <p class="cart-text"><b>Category: </b>@item.BookCategory</p>
                               <p class="cart-text"><b>ISBN: </b>@item.ISBN</p>

                 <!--              <p class="cart-text">
                                   <b>Status:</b>
                                  if(item.Pieces == 0){
                                       <span class="badge bg-succes text-white"> STOCK EMPTY</span>
                                   }else if(item.Pieces <=5){
                                       <span class="badge bg-succes text-white">LIMIT STOCK</span>
                                   }else{
                                       <span class="badge bg-succes text-white">IN STOCK</span>
                                   }
                               </p>
                               NOTE: MIGRATE DB AND UPDATE AFTER COLUMN PIECES in BOOK MODEL INSERTED
                               -->

                           </div>
                       </div>

                       <div class="col-md-12">
                           <div class="card-footer">
                            <p class="card-text d-flex justify-content-between">
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i>Add to Cart (@item.Price.ToString("c"))</a>
                                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">
                                       <i class="bi bi-eye-fill"></i>Show Details
                                </a>
                               </p>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
    }
</div>

@await Html.PartialAsync("_CreateItem","Books")